# Generated by Django 5.1.7 on 2025-07-08 18:40

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('admin_password', models.CharField(max_length=128)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('adhaar_img', models.FileField(blank=True, null=True, upload_to='adhaar/')),
                ('pan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_img', models.FileField(blank=True, null=True, upload_to='pancard/')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=255)),
                ('franchise_owner', models.CharField(max_length=255)),
                ('franchise_place', models.CharField(blank=True, max_length=255, null=True)),
                ('is_franchise', models.BooleanField(default=False)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('payment_status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('referral_code', models.CharField(default=users.models.generate_referral_code, max_length=8, unique=True)),
                ('aadhar', models.CharField(blank=True, max_length=50, null=True)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', message='Enter a valid account number.')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', message='Enter a valid IFSC code.')])),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffmodel')),
            ],
        ),
    ]
