# Generated by Django 5.2.4 on 2025-09-18 17:25

import django.core.validators
import django.db.models.deletion
import users.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('admin_password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('franchise_name', models.CharField(max_length=255)),
                ('franchise_owner', models.CharField(max_length=255)),
                ('franchise_place', models.CharField(blank=True, max_length=255, null=True)),
                ('franchise_type', models.CharField(choices=[('business_associate', 'Business Associate'), ('premium_franchise', 'Premium Franchise'), ('virtual_franchise', 'Virtual Franchise')], default='business_associate', max_length=20, verbose_name='Franchise Type')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='franchise_profiles/')),
                ('is_franchise', models.BooleanField(default=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('payment_status', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')])),
                ('password', models.CharField(max_length=128, null=True)),
                ('referral_code', models.CharField(default=users.models.generate_franchise_referral_code, max_length=8, unique=True, verbose_name='Franchise Referral Code')),
                ('aadhar', models.CharField(blank=True, max_length=50, null=True)),
                ('GST', models.CharField(blank=True, max_length=50, null=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', message='Enter a valid account number.')])),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', message='Enter a valid IFSC code.')])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_franchises', to='users.franchise', verbose_name='Referred By')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('allowance', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, verbose_name='Allowance')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Commission')),
                ('incentive', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Incentive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.franchise')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
