# Generated by Django 5.1 on 2025-08-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='adhaar_img',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='adhaar_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='pan_img',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='profile_completed',
        ),
        migrations.AddField(
            model_name='franchise',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='franchise_profiles/'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='employee_id',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
