# Generated by Django 5.2.4 on 2025-10-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Franchise Referral Code'),
        ),
    ]
