# Generated by Django 5.2.4 on 2025-08-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
        migrations.RenameField(
            model_name='staffmodel',
            old_name='is_staff',
            new_name='can_assign_franchises',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='adhaar_img',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='adhaar_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='pan_img',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='staffmodel',
            name='profile_completed',
        ),
        migrations.AddField(
            model_name='franchise',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='franchise_profiles/'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='can_create_loans',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='employee_id',
            field=models.CharField(default='EMP-1001', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
