# Generated by Django 5.1 on 2025-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_usermodel_remove_staffmodel_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
