# Generated by Django 5.1 on 2025-08-27 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_staffmodel_is_active_alter_staffmodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='franchise',
            name='franchise_type',
            field=models.CharField(choices=[('business_associate', 'Business Associate'), ('premium_franchise', 'Premium Franchise'), ('virtual_franchise', 'Virtual Franchise')], default='business_associate', max_length=20, verbose_name='Franchise Type'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Allowance')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission')),
                ('incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Incentive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.franchise')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
