# Generated by Django 5.1 on 2025-08-27 18:25

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_franchise_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_franchises', to='users.franchise', verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='referral_code',
            field=models.CharField(default=users.models.generate_franchise_referral_code, max_length=8, unique=True, verbose_name='Franchise Referral Code'),
        ),
    ]
