# Generated by Django 5.1 on 2025-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_franchise_referred_by_alter_franchise_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='is_franchise',
            field=models.BooleanField(default=True),
        ),
    ]
