# Generated by Django 5.1 on 2025-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_franchise_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
    ]
