# Generated by Django 5.1 on 2025-09-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminmodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Allowance'),
        ),
    ]
