# Generated by Django 5.1.7 on 2025-07-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSelectionModel',
            fields=[
                ('selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('selection', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAssignmentModel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to='users.adminmodel')),
                ('franchise_name', models.ManyToManyField(to='users.franchise')),
                ('staff_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='users.staffmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplicationModel',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('guaranter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_phoneno', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_job', models.CharField(blank=True, max_length=100, null=True)),
                ('guaranter_cibil_score', models.CharField(blank=True, max_length=50, null=True)),
                ('guaranter_cibil_issue', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't Know", "Don't Know")], default='No', max_length=20, null=True)),
                ('guaranter_it_payable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_score', models.CharField(blank=True, max_length=100, null=True)),
                ('cibil_issue', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't Know", "Don't Know")], default='No', max_length=20)),
                ('it_payable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('years', models.IntegerField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('followup_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('executive_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileno_1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobileno_2', models.CharField(blank=True, max_length=15, null=True)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffmodel')),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.bankmodel')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='users.franchise')),
                ('loan_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.loanmodel')),
                ('status_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loan.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='files/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='loan.loanapplicationmodel')),
            ],
        ),
    ]
