# Generated by Django 5.1 on 2025-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='mobileno_1',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='mobileno_2',
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address of the applicant', null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='reference_no_1',
            field=models.CharField(blank=True, help_text='Reference Number 1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='reference_no_2',
            field=models.CharField(blank=True, help_text='Reference Number 2', max_length=50, null=True),
        ),
    ]
