# Generated by Django 5.1 on 2025-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_remove_loanapplicationmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplicationmodel',
            options={'ordering': ['-created_at', '-form_id'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
