# Generated by Django 5.1 on 2025-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loanapplicationmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='workstatus',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Not selected', 'Not selected')], help_text='Staff work status (Accept/Reject/Pending)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='years',
            field=models.IntegerField(blank=True, help_text='Loan duration in years (1-30)', null=True),
        ),
    ]
