# Generated by Django 5.2.4 on 2025-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loanapplicationmodel_workstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplicationmodel',
            name='remarks',
            field=models.TextField(blank=True, help_text='Reason for status changes or notes from staff', null=True),
        ),
    ]
