# Generated by Django 5.1 on 2025-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Franchise',
        ),
    ]
