# Generated by Django 5.1.7 on 2025-05-29 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_staffassignmentmodel_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignmentmodel',
            name='franchise_mobile_no',
        ),
        migrations.RemoveField(
            model_name='staffassignmentmodel',
            name='franchise_place',
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='ac_no',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,18}$', message='Enter a valid account number.')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$', message='Enter a valid IFSC code.')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='mobile_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')]),
        ),
        migrations.RemoveField(
            model_name='staffassignmentmodel',
            name='franchise_name',
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a valid 10-digit mobile number.')]),
        ),
        migrations.AddField(
            model_name='staffassignmentmodel',
            name='franchise_name',
            field=models.ManyToManyField(to='UserApp.franchise'),
        ),
    ]
