# Generated by Django 5.1.7 on 2025-06-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_staffassignmentmodel_franchise_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
