# Generated by Django 5.1.7 on 2025-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_franchise_franchise_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='application_description',
        ),
        migrations.RemoveField(
            model_name='loanapplicationmodel',
            name='guaranter_years',
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='cibil_issue',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't Know", "Don't Know")], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='guaranter_cibil_issue',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ("Don't Know", "Don't Know")], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='guaranter_it_payable',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplicationmodel',
            name='it_payable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
